name: CI

on:
  push:
    branches: [ main ]
  pull_request:
    branches: [ main ]

jobs:
  backend-lint:
    name: Backend lint & typecheck
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - name: Set up Python
        uses: actions/setup-python@v4
        with:
          python-version: '3.11'
      - name: Install dependencies
        run: |
          python -m pip install --upgrade pip
          if [ -f backend/sales-api/requirements.txt ]; then pip install -r backend/sales-api/requirements.txt; fi
          pip install ruff mypy
      - name: Run ruff
        run: |
          ~/.local/bin/ruff backend/sales-api || true
      - name: Run mypy
        run: |
          ~/.local/bin/mypy backend/sales-api/app --ignore-missing-imports || true

  frontend-check:
    name: Frontend type-check
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - name: Set up Node.js
        uses: actions/setup-node@v4
        with:
          node-version: '18'
      - name: Install frontend deps
        working-directory: frontend
        run: npm ci
      - name: Run TypeScript type-check
        working-directory: frontend
        run: npm run type-check
