name: Build and publish images

on:
  push:
    branches: [ main ]

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4

      - name: Set up QEMU
        uses: docker/setup-qemu-action@v2

      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v2

      - name: Log in to GHCR
        uses: docker/login-action@v2
        with:
          registry: ghcr.io
          username: ${{ github.actor }}
          password: ${{ secrets.GITHUB_TOKEN }}

      - name: Build and push images
        uses: docker/build-push-action@v4
        with:
          context: .
          push: true
          platforms: linux/amd64,linux/arm64
          tags: |
            ghcr.io/${{ github.repository_owner }}/qoder2-sales-api:latest
            ghcr.io/${{ github.repository_owner }}/qoder2-frontend:latest
            ghcr.io/${{ github.repository_owner }}/qoder2-finance-api:latest
            ghcr.io/${{ github.repository_owner }}/qoder2-hr-api:latest
          file: backend/sales-api/Dockerfile.prod
